### ISSUE TITLE
[docker-build] using devDependencies

### ISSUE THREAD

**Issue by scriptcoded** [Dcard/yarn-plugins#21]
Hey, nice work with docker-build!

I'd really like to use it for our Nestjs project, but I have a few devDependencies that are required for the build stage. Is there any way to include these in one of my build steps, perhaps by loading two lockfiles, on with devDependencies and one without?

Best regards,
Malcolm

**Comment by haf** [comment]
@scriptcoded How did you solve this in the end?

**Comment by scriptcoded** [comment]
> @scriptcoded How did you solve this in the end?

I actually didn't use this plugin at all. We went for a more custom solution. I'll try and remember to post a brief description of what we did on Monday. Ping me if I forget :)

**Comment by haf** [comment]
@scriptcoded Thanks, good to know ;)
