### ISSUE TITLE
[docker-build] Fails to build TypeScript projects...

### ISSUE THREAD

**Issue by haf** [Dcard/yarn-plugins#22]
...due to not copying devDependencies; normally one use multi-stage builds, so to include devDependencies by default doesn't mean one has to let the `runner` have those too; instead `yarn install --prod` can be used in the runner, without copying `node_modules/` from the `builder`.

https://github.com/Dcard/yarn-plugins/issues/21 — also relevant.

**Comment by tommy351** [comment]
Duplicated #21

**Comment by haf** [comment]
Solution: upgrade to v0.8
